# 01 创建tensor

In [1]:
import torch

In [2]:
# 创建一个5*3未初始化的tensor

x1 = torch.empty(5, 3)
print(x1)

tensor([[1.8319e+25, 4.7562e+30, 4.5267e+21],
        [2.8231e+23, 7.6583e+28, 1.7753e+28],
        [1.9208e+31, 2.3715e+12, 7.3970e+20],
        [1.1430e+33, 2.0535e-19, 7.0952e+22],
        [2.0616e-19, 5.0843e+31, 1.1835e+22]])


In [3]:
# 创建一个5*3随机初始化的tensor

x2 = torch.rand(5, 3)
print(x2)

tensor([[0.7685, 0.4128, 0.4379],
        [0.9948, 0.7047, 0.4514],
        [0.3108, 0.4169, 0.3761],
        [0.5965, 0.4171, 0.3180],
        [0.6449, 0.2752, 0.8610]])


In [4]:
# 创建一个5*3全零tensor

x3 = torch.zeros(5, 3, dtype=torch.long)
print(x3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 直接通过数据创建tensor

x4 = torch.tensor([5.5, 3])
print(x4)
x5 = torch.tensor([[5, 6, 7],[8, 9, 0]])
print(x5)

tensor([5.5000, 3.0000])
tensor([[5, 6, 7],
        [8, 9, 0]])


In [6]:
# 通过已有的tensor来创造新的tensor

x6 = torch.rand(5, 3)
x7 = x6.new_ones(5, 3, dtype=torch.float64)
x8 = torch.randn_like(x6, dtype=torch.float)
print(x6)
print(x7)
print(x8)

tensor([[0.7364, 0.5075, 0.6360],
        [0.0756, 0.7810, 0.2041],
        [0.8348, 0.9046, 0.0209],
        [0.4402, 0.2408, 0.0985],
        [0.4054, 0.6090, 0.4128]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1296, -0.5921,  0.8504],
        [ 1.1745, -0.7176,  1.6882],
        [-0.4914,  1.7100,  0.6318],
        [ 2.8743,  0.7161, -0.7039],
        [ 1.3816,  0.7589, -0.7353]])


In [7]:
x9 = torch.rand(5, 3)
print(x9.size())
print(x9.shape)

torch.Size([5, 3])
torch.Size([5, 3])
