# 02 tensor的各种操作(一)

In [1]:
import torch

## 算术操作--加法

In [2]:
x1 = torch.rand(5, 3)
y1 = torch.rand(5, 3)
print(x1)
print(y1)

tensor([[0.2521, 0.8206, 0.6869],
        [0.6138, 0.7707, 0.7036],
        [0.9857, 0.9726, 0.1637],
        [0.8090, 0.1333, 0.6668],
        [0.2895, 0.7116, 0.2333]])
tensor([[0.4988, 0.2015, 0.2782],
        [0.9605, 0.6311, 0.1829],
        [0.1507, 0.8410, 0.0934],
        [0.4214, 0.4586, 0.9683],
        [0.2986, 0.8865, 0.1008]])


In [3]:
# 操作一
print(x1 + y1)

tensor([[0.7509, 1.0221, 0.9651],
        [1.5743, 1.4018, 0.8865],
        [1.1364, 1.8136, 0.2572],
        [1.2304, 0.5919, 1.6351],
        [0.5881, 1.5981, 0.3341]])


In [4]:
# 操作二
print(torch.add(x1, y1))
# 指定输出
result = torch.empty(5, 3)
torch.add(x1, y1, out=result)
print(result)

tensor([[0.7509, 1.0221, 0.9651],
        [1.5743, 1.4018, 0.8865],
        [1.1364, 1.8136, 0.2572],
        [1.2304, 0.5919, 1.6351],
        [0.5881, 1.5981, 0.3341]])
tensor([[0.7509, 1.0221, 0.9651],
        [1.5743, 1.4018, 0.8865],
        [1.1364, 1.8136, 0.2572],
        [1.2304, 0.5919, 1.6351],
        [0.5881, 1.5981, 0.3341]])


In [5]:
# 操作三
y1.add_(x1)
print(y1)

tensor([[0.7509, 1.0221, 0.9651],
        [1.5743, 1.4018, 0.8865],
        [1.1364, 1.8136, 0.2572],
        [1.2304, 0.5919, 1.6351],
        [0.5881, 1.5981, 0.3341]])


## 索引

In [6]:
x2 = torch.rand(5, 3)
y2 = torch.rand(5, 3)
print(x2)
print(y2)

tensor([[0.5822, 0.5563, 0.2445],
        [0.4907, 0.4946, 0.9142],
        [0.7150, 0.8503, 0.0614],
        [0.2815, 0.1887, 0.5431],
        [0.5371, 0.7168, 0.6596]])
tensor([[0.0636, 0.3147, 0.0134],
        [0.4604, 0.0982, 0.6017],
        [0.1311, 0.0521, 0.6543],
        [0.0953, 0.7787, 0.2540],
        [0.3577, 0.8990, 0.7495]])


In [7]:
y2 = x2[0, : ]
y2 += 1
print(y2)
print(x2[0, : ])
# 索引结果与原数据共享内存

tensor([1.5822, 1.5563, 1.2445])
tensor([1.5822, 1.5563, 1.2445])


## 改变形状

In [8]:
x3 = torch.rand(5, 3)
print(x3)

tensor([[0.6447, 0.7714, 0.1413],
        [0.3388, 0.2834, 0.1316],
        [0.0624, 0.9471, 0.1251],
        [0.2784, 0.4874, 0.1881],
        [0.4288, 0.8884, 0.5604]])


In [9]:
y3 = x3.view(15)
z3 = x3.view(-1, 5)
print(x3, x3.size())
print(y3, y3.size())
print(z3, z3.size())

tensor([[0.6447, 0.7714, 0.1413],
        [0.3388, 0.2834, 0.1316],
        [0.0624, 0.9471, 0.1251],
        [0.2784, 0.4874, 0.1881],
        [0.4288, 0.8884, 0.5604]]) torch.Size([5, 3])
tensor([0.6447, 0.7714, 0.1413, 0.3388, 0.2834, 0.1316, 0.0624, 0.9471, 0.1251,
        0.2784, 0.4874, 0.1881, 0.4288, 0.8884, 0.5604]) torch.Size([15])
tensor([[0.6447, 0.7714, 0.1413, 0.3388, 0.2834],
        [0.1316, 0.0624, 0.9471, 0.1251, 0.2784],
        [0.4874, 0.1881, 0.4288, 0.8884, 0.5604]]) torch.Size([3, 5])


In [10]:
# .view()改变tensor形状，但新tensor与原tensor共享同一处内存
x3 += 1
print(x3)
print(y3)

tensor([[1.6447, 1.7714, 1.1413],
        [1.3388, 1.2834, 1.1316],
        [1.0624, 1.9471, 1.1251],
        [1.2784, 1.4874, 1.1881],
        [1.4288, 1.8884, 1.5604]])
tensor([1.6447, 1.7714, 1.1413, 1.3388, 1.2834, 1.1316, 1.0624, 1.9471, 1.1251,
        1.2784, 1.4874, 1.1881, 1.4288, 1.8884, 1.5604])


In [11]:
# .clone()复制时，新tenor与原tenor没有共享同一处内存
x_copy = x3.clone().view(15)
x3 -= 1
print(x_copy)
print(x3)

tensor([1.6447, 1.7714, 1.1413, 1.3388, 1.2834, 1.1316, 1.0624, 1.9471, 1.1251,
        1.2784, 1.4874, 1.1881, 1.4288, 1.8884, 1.5604])
tensor([[0.6447, 0.7714, 0.1413],
        [0.3388, 0.2834, 0.1316],
        [0.0624, 0.9471, 0.1251],
        [0.2784, 0.4874, 0.1881],
        [0.4288, 0.8884, 0.5604]])


In [12]:
# .item()将标量tensor转换为python内的数据
x4 = torch.randn(1)
print(x4)
print(x4.item())

tensor([1.9515])
1.9515163898468018
