# 03 tensor的各种操作(二)

In [1]:
import torch

## 广播机制

In [2]:
x1 = torch.arange(1, 3).view(1, 2)   # x1是1行2列的矩阵
y1 = torch.arange(1, 4).view(3, 1)   # y1是3行1列的矩阵
print(x1)
print(y1)
print(x1 + y1)
# x1的一行中的两个元素被复制后参与了x1+y1第二，三行的计算；而y1的一列的三个元素被复制后参与了x1+y1第二列的计算

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 运算时的内存情况

In [3]:
# 直接运算

x2 = torch.tensor([1, 2])
y2 = torch.tensor([3, 4])
id_before1 = id(y2)
print(id_before1)
y2 = y2 + x2
print(id(y2))
print(id(y2) == id_before1)

1439667485656
1439636590328
False


In [4]:
# 通过索引来替换操作

x3 = torch.tensor([1, 2])
y3 = torch.tensor([3, 4])
id_before2 = id(y3)
print(id_before2)
y3[:] = y3 + x3
print(id(y3))
print(id(y3) == id_before2)

1439667516424
1439667516424
True


In [5]:
# 通过使用函数中自带的参数out来指定内存地址

x4 = torch.tensor([1, 2])
y4 = torch.tensor([3, 4])
id_before3 = id(y4)
print(id_before3)
torch.add(x4, y4, out=y4)
print(id(y4))
print(id(y4) == id_before3)

1439667536264
1439667536264
True


## tensor和numpy间的相互转换

### tensor转换成numpy

In [6]:
a1 = torch.ones(5)
b1 = a1.numpy()
print(a1)
print(b1)
print(id(a1) == id(b1))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
False


In [7]:
a1 += 1
print(a1)
print(b1)
print(id(a1) == id(b1))

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
False


In [8]:
b1 += 1
print(a1)
print(b1)
print(id(a1) == id(b1))

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]
False


### numpy转换成tensor

In [9]:
import numpy as np
a2 = np.ones(5)
b2 = torch.from_numpy(a2)
print(a2)
print(b2)
print(id(a2) == id(b2))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
False


In [10]:
a2 += 1
print(a2)
print(b2)
print(id(a2) == id(b2))

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
False


In [11]:
b2 += 1
print(a2)
print(b2)
print(id(a2) == id(b2))

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
False


In [12]:
# 直接torch.tensor()的方法

a = np.ones(5)
b = torch.tensor(a)
print(a)
print(b)
print(id(a) == id(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
False
