# 04 自动求梯度(一)

In [1]:
import torch

将tensor的属性.requires_grad设置为True，开始追踪其上所有的操作

完成一系列操作后，用.backward()完成所有的梯度计算；tensor的梯度将累积到.grad属性中

用.detach()来停止追踪；也可以用with torch.no_grad()将不想追踪的代码块包裹起来

tensor与function结合起来可以创建一个记录有整个计算过程的有向无环图

每个tensor都有一个.grad_fn属性

若该tensor是由某个运算得到的，则.grad_fn返回一个与该运算过程有关的对象

否则,.grad_fn返回None

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [3]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# 像x这种是直接创建的，被称为叶子节点，叶子节点的grad_fn是None
print(x.is_leaf)
print(y.is_leaf)

True
False


In [5]:
# 复杂度运算
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


## 通过.requires_grad()的方法来改变requires_grad属性

In [6]:
a = torch.randn(2, 2)   # 默认requires_grad=False
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.requires_grad)
print(b.grad_fn)

False
True
True
